const list = [
  {company: 'Facebook', position: 'Software Engineer', location: 'Santa Clara, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porttitor ornare urna eget ornare. Suspendisse finibus viverra nisi id pellentesque. Nullam eget scelerisque lorem, sed rhoncus tellus. Praesent luctus quis mi id volutpat.' },
  {company: 'Apple', position: 'Front-end Engineer', location: 'Cupertino, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus enim neque, lobortis non dui ac, faucibus vestibulum nibh. Integer in mi pulvinar, viverra mi ac, euismod diam. Suspendisse tincidunt elementum libero eget scelerisque.' },
  {company: 'Amazon', position: 'Back-end Engineer', location: 'San Francisco, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porttitor ornare urna eget ornare. Suspendisse finibus viverra nisi id pellentesque. Nullam eget scelerisque lorem, sed rhoncus tellus. Praesent luctus quis mi id volutpat.' },
  {company: 'Netflix', position: 'Full-stack Engineer', location: 'Santa Clara, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus enim neque, lobortis non dui ac, faucibus vestibulum nibh. Integer in mi pulvinar, viverra mi ac, euismod diam. Suspendisse tincidunt elementum libero eget scelerisque.' },
  {company: 'Google', position: 'Software Engineer', location: 'San Francisco, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porttitor ornare urna eget ornare. Suspendisse finibus viverra nisi id pellentesque. Nullam eget scelerisque lorem, sed rhoncus tellus. Praesent luctus quis mi id volutpat.' },
  {company: 'Facebook', position: 'Software Engineer', location: 'Santa Clara, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porttitor ornare urna eget ornare. Suspendisse finibus viverra nisi id pellentesque. Nullam eget scelerisque lorem, sed rhoncus tellus. Praesent luctus quis mi id volutpat.' },
  {company: 'Apple', position: 'Front-end Engineer', location: 'Cupertino, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus enim neque, lobortis non dui ac, faucibus vestibulum nibh. Integer in mi pulvinar, viverra mi ac, euismod diam. Suspendisse tincidunt elementum libero eget scelerisque.' },
  {company: 'Amazon', position: 'Back-end Engineer', location: 'San Francisco, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porttitor ornare urna eget ornare. Suspendisse finibus viverra nisi id pellentesque. Nullam eget scelerisque lorem, sed rhoncus tellus. Praesent luctus quis mi id volutpat.' },
  {company: 'Netflix', position: 'Full-stack Engineer', location: 'Santa Clara, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus enim neque, lobortis non dui ac, faucibus vestibulum nibh. Integer in mi pulvinar, viverra mi ac, euismod diam. Suspendisse tincidunt elementum libero eget scelerisque.' },
  {company: 'Google', position: 'Software Engineer', location: 'San Francisco, CA', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In porttitor ornare urna eget ornare. Suspendisse finibus viverra nisi id pellentesque. Nullam eget scelerisque lorem, sed rhoncus tellus. Praesent luctus quis mi id volutpat.' }
]

export default list;